version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 35
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
  git-legal:
    enabled: true
    checks:
      Compatibility/No licenses:
        enabled: false
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
  - "package-lock.json"
  - "composer.lock"
  - ".circleci/"
  - "documentation/"
  - "tests/_reports/"
  - "tests/bats/_helpers/bats-assert/"
  - "tests/bats/_helpers/bats-support/"
  - "vendor/"
