version: '3.4'

services:
  app:
    build: .
    restart: always
    container_name: ${APP_NAME:-corporate}_app
    ports:
      - ${PORT_PREFIX:-}9080:80
    depends_on:
      - database
      - redis
    networks:
      - scrw_corporate
    environment:
      - DB_HOST=database
      - DB_USER=${DB_USER:-scrw_db_user}
      - DB_PASSWORD=${DB_PASSWORD:-scrw_db_password}
      - DB_NAME=${DB_NAME:-scrw_db}
      - REDIS_SERVERS=redis
      - WP_ENV=${WP_ENV:-local}
      - WP_HOME=${WP_HOME:-http://localhost:9080}
      - WP_CACHE=${WP_CACHE:-false}
      - AWS_IAM_KEY=AWS_IAM_KEY
      - AWS_IAM_SECRET=AWS_IAM_SECRET
      - AWS_S3_BUCKET=AWS_S3_BUCKET
      - AWS_S3_BUCKET_REGION=AWS_S3_BUCKET_REGION
      - AWS_CLOUDFRONT_DOMAIN=AWS_CLOUDFRONT_DOMAIN
      - AWS_CLOUDFRONT_ID=AWS_CLOUDFRONT_ID
    #labels:
    #  - 'scrw.backend=${APP_NAME}'
    #  - 'scrw.docker.network=scrw_wp_external'
    #  - 'scrw.frontend.rule=Host:${APP_NAME}'
    #  - 'scrw.enable=true'
    #  - 'scrw.port=80'
    #volumes:
      #- ./local/public:/home/appuser/app/web/app/uploads
      

      #- db-data:/home/appuser/foo
      
      #- .cache/app/storage/cache:/home/appuser/app/web/.cache
      #- .cache/app/storage/configs:/home/appuser/app/web/.configs
      
      # - ./config/nginx:/etc/nginx/conf.d
      
      #- .cache/app/logs/nginx:/var/log/nginx
      #- .cache/app/logs/php:/var/log/php
      #- .cache/app/logs/supervisor:/var/log/supervisor
      
      #- .cache/app/uploads:/home/appuser/app/web/app/uploads
      # - type: bind
      #   source: /home/appuser/app/web/app/uploads
      #   target: .cache/app/uploads

  database:
    image: mysql:latest
    container_name: ${APP_NAME:-corporate}_mysql
    restart: always
    ports:
      - ${PORT_PREFIX:-}3306:3306
    command: [
    # '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - scrw_corporate
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER: ${DB_USER:-scrw_db_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-scrw_db_password}
      MYSQL_DATABASE: ${DB_NAME:-scrw_db}
    volumes:
      - '.cache/docker/database:/var/lib/mysql'

  redis:
    image: redis:5.0.8
    container_name: ${APP_NAME}_redis
    restart: always
    ports:
      - ${PORT_PREFIX:-}6379:6379
    networks:
      - scrw_corporate
    #volumes:
    #  - '.cache/redis:/var/lib/redis'


  adminer:
    image: adminer:latest
    restart: always
    ports:
      - ${PORT_PREFIX:-}9081:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DEFAULT_DB_NAME: ${DB_NAME:-scrw_db}
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    networks:
      - scrw_corporate

networks:
  scrw_corporate:
    driver: bridge


#volumes:
#    db-data:

# volumes:
#   # mysql_data:
#   #   driver: local
#   mysql:
#     driver: local
#     driver_opts:
#       device: $PWD/.cache/




# 172.28.0.2
